# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            如是我聞
description:      Keep Calm and Follow the Code
url:              http://ztpala.com
domain:           ztpala.com
email:            ztpala@gmail.com
twitter_username: ztpala
github_username:  pala
github_repo:      https://github.com/pala/pala.github.io
google_analytics: UA-5531632-1
timezone:         America/New_York
subscribe:        http://feed.ztpala.com
baseurl: ""
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME
